name: DLA Public Site Deploy
on: 
  push:
    branches:
      main
  pull_request:
    branches:
      main
jobs:
    deploy:
      # Deploy to newprd01 with SSH
      runs-on: [self-hosted, vlcdhp02]
      strategy: 
        matrix:
            node-version: [21]
      steps:
        - uses: actions/checkout@v3
        - run: |
            if [[ ! -e /srv/node/logs/dlalogs.txt ]]; then
                mkdir -p /srv/node/logs
                touch /srv/node/logs/dlalogs.txt
            fi
            cd /srv/node/dla-public-site/
            pm2 stop dla_public
            git stash
            git pull
            npm install
            pm2 start -i max bin/dla_public.js
